main08-1: main08-1.c llist.o llist-plus.o
	$(CC) -o main08-1 main08-1.c llist.o llist-plus.o
llist.o: llist.c llist.h
	$(CC) -c llist.c llist.h
llist-plus.o: llist-plus.c llist-plus.h
	$(CC) -c llist-plus.c llist-plus.h
