main07-2: main07-2.o SortStudent.o
	$(CC) -o main07-2 main07-2.o SortStudent.o
main07-2.o: main07-2.c SortStudent.h
	$(CC) -c main07-2.c
SortStudent.o: SortStudent.c SortStudent.h
	$(CC) -c SortStudent.c
