main06-3: main06-3.o stack.o queue.o
	$(CC) -o main06-3 main06-3.o stack.o queue.o
main06-3.o: main06-3.c stack.h queue.h
	$(CC) -c main06-3.c
stack.o: stack.c stack.h
	$(CC) -c stack.c
queue.o: queue.c queue.h
	$(CC) -c queue.c
